# -*- coding: utf-8 -*-
"""assignment1.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dx1RUBuGa_xFtP4UV4W9JpBN8pV8_QMC
"""

import numpy as np
from scipy.optimize import fsolve
def func(X):
  x=X[0]
  y=X[1]
  l=X[2]
  return  ((x**2)*y)-l*(x**2+y**2-1)

def dfunc(X):
  dlambda=np.zeros(len(X))
  h=1e-3
  for i in range(len(X)):
    dX=np.zeros(len(X))
    dX[i]=h
    dlambda[i]=(func(X+dX)-func(X-dX))/(2*h)
  return dlambda
X1=fsolve(dfunc, [1,1,0])
print (X1,func(X1))
X2=fsolve(dfunc, [-1,-1,0])
print (X2,func(X2))

1e-3

